# Generated by Django 4.2.1 on 2023-07-06 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_buyer', '0002_seller_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_price', models.IntegerField()),
                ('p_image', models.FileField(default='msm.jpg', upload_to='Product/')),
                ('p_qut', models.IntegerField()),
                ('p_dec', models.TextField(max_length=500)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_buyer.seller_user')),
            ],
        ),
    ]
