# Generated by Django 4.2.1 on 2023-06-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(default='msm.jpg', upload_to='media/'),
        ),
    ]
