# Generated by Django 4.2.1 on 2023-07-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
