# Generated by Django 4.2.1 on 2023-07-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_buyer', '0003_product'),
        ('app_buyer', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qut', models.IntegerField(default=0)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buyer.user')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_buyer.product')),
            ],
        ),
    ]
