# Generated by Django 4.2.1 on 2023-07-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0010_cart_pro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=10)),
                ('MiddleName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=50)),
                ('postelcode', models.IntegerField(default=0)),
                ('State', models.CharField(max_length=10)),
                ('PhoneNumber', models.IntegerField(default=0)),
            ],
        ),
    ]
